# SPDX-License-Identifier: APACHE-2.0
# SPDX-FileCopyrightText: 2026 Nirapod Contributors

name: Audit

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  nirapod-audit:
    name: Nirapod Security & Compliance Audit
    uses: nirapod-labs/nirapod-audit/.github/workflows/reusable-audit.yml@24f6427ef1c7e46a206aea4cbcc900dad6595316
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
      statuses: write
    with:
      working_directory: packages/core
